/** @type {import('tailwindcss').Config} */
import catppuccin from "@catppuccin/daisyui";
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      "light",
      "dark",
      {
        sunset: {
          ...require("daisyui/src/theming/themes")["sunset"],
          primary: "#155e75",
          "--rounded-badge": "1.9rem",
        },
      },
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "halloween",
      catppuccin("macchiato", { primary: "mauve", secondary: "pink" }),
      catppuccin("mocha", { primary: "mauve", secondary: "pink" }),
      catppuccin("latte", { primary: "mauve", secondary: "pink" }),
      catppuccin("frappe", { primary: "mauve", secondary: "pink" }),
      {
        lunaar: {
          primary: "rgb(180, 105, 255)",
          secondary: "#f6d860",
          accent: "#37cdbe",
          neutral: "#3d4451",
          "base-100": "#3b039c",
          background: "#3b039c", // Matches --bg
          "background-alt": "rgb(69, 9, 174)",
          "logo-color": "#6b09ac",
          "button-color": "rgb(180, 105, 255)",
          "text-color": "#fff",

          "--rounded-box": "1rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
          "--animation-btn": "0.25s",
          "--animation-input": "0.2s",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.5rem",
          "--background-filter": "blur(3px) brightness(80%)",
        },
        surfshark: {
          primary: "#1EBFBF",
          secondary: "#2dd4bf",
          accent: "#00ffff",
          neutral: "#6b7280",
          "base-100": "#1f2937",
          info: "#7dd3fc",
          success: "#00ff00",
          warning: "#fde047",
          error: "#ff0000",
        },
        youtube: {
          primary: "#ff0000",
          secondary: "#991b1b",
          accent: "#fbbf24",
          neutral: "#ff0000",
          "base-100": "#2e2e2e",
          info: "#38bdf8",
          success: "#00ff00",
          warning: "#facc15",
          error: "#fb7185",
        },
      },
      // catppuccin("latte"),
      // catppuccin("frappe"),
      // catppuccin("macchiato"),
      // catppuccin("mocha", { primary: "mauve", secondary: "rosewater" }),
    ],
  },
};
